//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManejoArchivos.WSConsultaComprobantesOnLine {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.feds/")]
    public partial class Exception : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.feds/", ConfigurationName="WSConsultaComprobantesOnLine.ConsultService")]
    public interface ConsultService {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ManejoArchivos.WSConsultaComprobantesOnLine.Exception), Action="", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ManejoArchivos.WSConsultaComprobantesOnLine.getDocumentoPDFResponse getDocumentoPDF(ManejoArchivos.WSConsultaComprobantesOnLine.getDocumentoPDF request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ManejoArchivos.WSConsultaComprobantesOnLine.getDocumentoPDFResponse> getDocumentoPDFAsync(ManejoArchivos.WSConsultaComprobantesOnLine.getDocumentoPDF request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ManejoArchivos.WSConsultaComprobantesOnLine.Exception), Action="", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ManejoArchivos.WSConsultaComprobantesOnLine.getDocumentoXMLResponse getDocumentoXML(ManejoArchivos.WSConsultaComprobantesOnLine.getDocumentoXML request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ManejoArchivos.WSConsultaComprobantesOnLine.getDocumentoXMLResponse> getDocumentoXMLAsync(ManejoArchivos.WSConsultaComprobantesOnLine.getDocumentoXML request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ManejoArchivos.WSConsultaComprobantesOnLine.Exception), Action="", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ManejoArchivos.WSConsultaComprobantesOnLine.getDocumentoCDRResponse getDocumentoCDR(ManejoArchivos.WSConsultaComprobantesOnLine.getDocumentoCDR request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ManejoArchivos.WSConsultaComprobantesOnLine.getDocumentoCDRResponse> getDocumentoCDRAsync(ManejoArchivos.WSConsultaComprobantesOnLine.getDocumentoCDR request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDocumentoPDF", WrapperNamespace="http://ws.feds/", IsWrapped=true)]
    public partial class getDocumentoPDF {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.feds/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ruc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.feds/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.feds/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string serie;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.feds/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string correlativo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.feds/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fecha;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.feds/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string total;
        
        public getDocumentoPDF() {
        }
        
        public getDocumentoPDF(string ruc, string tipo, string serie, string correlativo, string fecha, string total) {
            this.ruc = ruc;
            this.tipo = tipo;
            this.serie = serie;
            this.correlativo = correlativo;
            this.fecha = fecha;
            this.total = total;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDocumentoPDFResponse", WrapperNamespace="http://ws.feds/", IsWrapped=true)]
    public partial class getDocumentoPDFResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.feds/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getDocumentoPDFResponse() {
        }
        
        public getDocumentoPDFResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDocumentoXML", WrapperNamespace="http://ws.feds/", IsWrapped=true)]
    public partial class getDocumentoXML {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.feds/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ruc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.feds/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.feds/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string serie;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.feds/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string correlativo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.feds/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fecha;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.feds/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string total;
        
        public getDocumentoXML() {
        }
        
        public getDocumentoXML(string ruc, string tipo, string serie, string correlativo, string fecha, string total) {
            this.ruc = ruc;
            this.tipo = tipo;
            this.serie = serie;
            this.correlativo = correlativo;
            this.fecha = fecha;
            this.total = total;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDocumentoXMLResponse", WrapperNamespace="http://ws.feds/", IsWrapped=true)]
    public partial class getDocumentoXMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.feds/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getDocumentoXMLResponse() {
        }
        
        public getDocumentoXMLResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDocumentoCDR", WrapperNamespace="http://ws.feds/", IsWrapped=true)]
    public partial class getDocumentoCDR {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.feds/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ruc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.feds/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.feds/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string serie;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.feds/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string correlativo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.feds/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fecha;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.feds/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string total;
        
        public getDocumentoCDR() {
        }
        
        public getDocumentoCDR(string ruc, string tipo, string serie, string correlativo, string fecha, string total) {
            this.ruc = ruc;
            this.tipo = tipo;
            this.serie = serie;
            this.correlativo = correlativo;
            this.fecha = fecha;
            this.total = total;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDocumentoCDRResponse", WrapperNamespace="http://ws.feds/", IsWrapped=true)]
    public partial class getDocumentoCDRResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.feds/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getDocumentoCDRResponse() {
        }
        
        public getDocumentoCDRResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ConsultServiceChannel : ManejoArchivos.WSConsultaComprobantesOnLine.ConsultService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConsultServiceClient : System.ServiceModel.ClientBase<ManejoArchivos.WSConsultaComprobantesOnLine.ConsultService>, ManejoArchivos.WSConsultaComprobantesOnLine.ConsultService {
        
        public ConsultServiceClient() {
        }
        
        public ConsultServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConsultServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ManejoArchivos.WSConsultaComprobantesOnLine.getDocumentoPDFResponse ManejoArchivos.WSConsultaComprobantesOnLine.ConsultService.getDocumentoPDF(ManejoArchivos.WSConsultaComprobantesOnLine.getDocumentoPDF request) {
            return base.Channel.getDocumentoPDF(request);
        }
        
        public string getDocumentoPDF(string ruc, string tipo, string serie, string correlativo, string fecha, string total) {
            ManejoArchivos.WSConsultaComprobantesOnLine.getDocumentoPDF inValue = new ManejoArchivos.WSConsultaComprobantesOnLine.getDocumentoPDF();
            inValue.ruc = ruc;
            inValue.tipo = tipo;
            inValue.serie = serie;
            inValue.correlativo = correlativo;
            inValue.fecha = fecha;
            inValue.total = total;
            ManejoArchivos.WSConsultaComprobantesOnLine.getDocumentoPDFResponse retVal = ((ManejoArchivos.WSConsultaComprobantesOnLine.ConsultService)(this)).getDocumentoPDF(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ManejoArchivos.WSConsultaComprobantesOnLine.getDocumentoPDFResponse> ManejoArchivos.WSConsultaComprobantesOnLine.ConsultService.getDocumentoPDFAsync(ManejoArchivos.WSConsultaComprobantesOnLine.getDocumentoPDF request) {
            return base.Channel.getDocumentoPDFAsync(request);
        }
        
        public System.Threading.Tasks.Task<ManejoArchivos.WSConsultaComprobantesOnLine.getDocumentoPDFResponse> getDocumentoPDFAsync(string ruc, string tipo, string serie, string correlativo, string fecha, string total) {
            ManejoArchivos.WSConsultaComprobantesOnLine.getDocumentoPDF inValue = new ManejoArchivos.WSConsultaComprobantesOnLine.getDocumentoPDF();
            inValue.ruc = ruc;
            inValue.tipo = tipo;
            inValue.serie = serie;
            inValue.correlativo = correlativo;
            inValue.fecha = fecha;
            inValue.total = total;
            return ((ManejoArchivos.WSConsultaComprobantesOnLine.ConsultService)(this)).getDocumentoPDFAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ManejoArchivos.WSConsultaComprobantesOnLine.getDocumentoXMLResponse ManejoArchivos.WSConsultaComprobantesOnLine.ConsultService.getDocumentoXML(ManejoArchivos.WSConsultaComprobantesOnLine.getDocumentoXML request) {
            return base.Channel.getDocumentoXML(request);
        }
        
        public string getDocumentoXML(string ruc, string tipo, string serie, string correlativo, string fecha, string total) {
            ManejoArchivos.WSConsultaComprobantesOnLine.getDocumentoXML inValue = new ManejoArchivos.WSConsultaComprobantesOnLine.getDocumentoXML();
            inValue.ruc = ruc;
            inValue.tipo = tipo;
            inValue.serie = serie;
            inValue.correlativo = correlativo;
            inValue.fecha = fecha;
            inValue.total = total;
            ManejoArchivos.WSConsultaComprobantesOnLine.getDocumentoXMLResponse retVal = ((ManejoArchivos.WSConsultaComprobantesOnLine.ConsultService)(this)).getDocumentoXML(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ManejoArchivos.WSConsultaComprobantesOnLine.getDocumentoXMLResponse> ManejoArchivos.WSConsultaComprobantesOnLine.ConsultService.getDocumentoXMLAsync(ManejoArchivos.WSConsultaComprobantesOnLine.getDocumentoXML request) {
            return base.Channel.getDocumentoXMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<ManejoArchivos.WSConsultaComprobantesOnLine.getDocumentoXMLResponse> getDocumentoXMLAsync(string ruc, string tipo, string serie, string correlativo, string fecha, string total) {
            ManejoArchivos.WSConsultaComprobantesOnLine.getDocumentoXML inValue = new ManejoArchivos.WSConsultaComprobantesOnLine.getDocumentoXML();
            inValue.ruc = ruc;
            inValue.tipo = tipo;
            inValue.serie = serie;
            inValue.correlativo = correlativo;
            inValue.fecha = fecha;
            inValue.total = total;
            return ((ManejoArchivos.WSConsultaComprobantesOnLine.ConsultService)(this)).getDocumentoXMLAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ManejoArchivos.WSConsultaComprobantesOnLine.getDocumentoCDRResponse ManejoArchivos.WSConsultaComprobantesOnLine.ConsultService.getDocumentoCDR(ManejoArchivos.WSConsultaComprobantesOnLine.getDocumentoCDR request) {
            return base.Channel.getDocumentoCDR(request);
        }
        
        public string getDocumentoCDR(string ruc, string tipo, string serie, string correlativo, string fecha, string total) {
            ManejoArchivos.WSConsultaComprobantesOnLine.getDocumentoCDR inValue = new ManejoArchivos.WSConsultaComprobantesOnLine.getDocumentoCDR();
            inValue.ruc = ruc;
            inValue.tipo = tipo;
            inValue.serie = serie;
            inValue.correlativo = correlativo;
            inValue.fecha = fecha;
            inValue.total = total;
            ManejoArchivos.WSConsultaComprobantesOnLine.getDocumentoCDRResponse retVal = ((ManejoArchivos.WSConsultaComprobantesOnLine.ConsultService)(this)).getDocumentoCDR(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ManejoArchivos.WSConsultaComprobantesOnLine.getDocumentoCDRResponse> ManejoArchivos.WSConsultaComprobantesOnLine.ConsultService.getDocumentoCDRAsync(ManejoArchivos.WSConsultaComprobantesOnLine.getDocumentoCDR request) {
            return base.Channel.getDocumentoCDRAsync(request);
        }
        
        public System.Threading.Tasks.Task<ManejoArchivos.WSConsultaComprobantesOnLine.getDocumentoCDRResponse> getDocumentoCDRAsync(string ruc, string tipo, string serie, string correlativo, string fecha, string total) {
            ManejoArchivos.WSConsultaComprobantesOnLine.getDocumentoCDR inValue = new ManejoArchivos.WSConsultaComprobantesOnLine.getDocumentoCDR();
            inValue.ruc = ruc;
            inValue.tipo = tipo;
            inValue.serie = serie;
            inValue.correlativo = correlativo;
            inValue.fecha = fecha;
            inValue.total = total;
            return ((ManejoArchivos.WSConsultaComprobantesOnLine.ConsultService)(this)).getDocumentoCDRAsync(inValue);
        }
    }
}
